coverage:
  range: 50..80
  round: down
  precision: 0
  status:
    project:
      default:
        target: auto
        threshold: 0%
        base: auto
        if_ci_failed: error #success, failure, error, ignore
        informational: false
        only_pulls: false